### ISSUE TITLE
Packet cell search problem

### ISSUE THREAD

**Issue by ashuralyk** [synapseweb3/forcerelay-ckb-sdk#13]
https://github.com/synapseweb3/forcerelay-ckb-sdk/blob/main/src/search.rs#L45

the first searched packet cells may not be my expectation, I prefer to rollback to the previous process

**Comment by blckngm** [comment]
Just [filter](https://docs.rs/futures/latest/futures/stream/trait.TryStreamExt.html#method.try_filter) the cells.

**Comment by blckngm** [comment]
`PacketCell::subscribe(...).try_filter(|p| futures::future::ready(p.is_ack_packet()))`.
