### ISSUE TITLE
rename suggestion

### ISSUE THREAD

**Issue by Flouse** [synapseweb3/forcerelay-ckb-sdk#30]
https://github.com/synapseweb3/forcerelay-ckb-sdk/blob/1a1c5c1debc6d7e10f3093479f87727abf35e01b/examples/sudt-transfer.rs#L98-L126

1. sdk_config.user_lock_script -> sdk_config.st_cell_lock_script
2. user_lock_script -> sender_lock_script

**Comment by blckngm** [comment]
SDK config `user_lock_script` is from sdk design doc. I think it should be renamed to `module_lock_script`. SDK can be used with various modules and are not specific to sudt-transfer.

**Comment by Flouse** [comment]
> module_lock_script

Yep. `sdk_config.module_lock_script` is a better name.
