### ISSUE TITLE
if RecvPacket cell is pending, `sudt-transfer` may exit with 0 packets found

### ISSUE THREAD

**Issue by ashuralyk** [synapseweb3/forcerelay-ckb-sdk#37]
<img width="595" alt="image" src="https://github.com/synapseweb3/forcerelay-ckb-sdk/assets/3871265/c5eea501-0f9d-4317-83b7-b68d844840cb">

**Comment by blckngm** [comment]
This is with https://github.com/synapseweb3/forcerelay-ckb-sdk/pull/28?

**Comment by ashuralyk** [comment]
> This is with #28?

yes, it is
