### ISSUE TITLE
Inappropriate packet subscribe search prefix

### ISSUE THREAD

**Issue by ashuralyk** [synapseweb3/forcerelay-ckb-sdk#7]
1. the prefix of packet search key shouldn't set `sequence` field https://github.com/synapseweb3/forcerelay-ckb-sdk/blob/main/src/config.rs#L85
2. I'm not sure searching packet cells in a range of block is a proper way

**Comment by blckngm** [comment]
Sequence is not included because args is `packet_args.get_search_args(/* search_all */ true)`.

**Comment by blckngm** [comment]
Problem is in cursor usage.

**Comment by blckngm** [comment]
Fixed.

**Comment by blckngm** [comment]
Using block range without cursor is problematic when there are *many* cells in the search range. Cells not returned because of the limit will be permanently skipped.
